name: lf_sling

services:
  sling:
    image: slingdata/sling:latest
    container_name: sling
    environment:
      - SLING_SRC_DB=${SLING_SRC_DB} # use docker compose run -e SLING_SRC_DB=value
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./replication.yml:/app/replication.yml
      - ./data/:/data/
      - ./duckdb/:/home/sling/.duckdb/
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
