name: lf_sling

services:
  sling:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sling
    environment:
      - SLING_SRC_DB=${SLING_SRC_DB}
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - ${SLING_REPLICATION_PATH:-./replication.yml}:/app/replication.yml
      - ${SLING_OUTPUT_DIR:-./data/}:/data/
    entrypoint: ["tail", "-f", "/dev/null"]
